# Preface {.unnumbered}

Tropical forests vary widely in their precipitation regimes and seasonal water availability, but high-quality in situ (ground-based) meteorological data are rare, and few studies have evaluated the performance of global gridded climate products in the tropics. We compared the performance of eleven high-resolution gridded climate products against in situ datasets spanning high rainfall variation in central Panama. The gridded products almost all captured the broad trends of spatial and seasonal rainfall variation in central Panama, and all underestimated precipitation in the wettest sites, especially in the dry season, but differed widely in their performance. Seasonal and interannual variation were best captured by CHIRPSv2, while spatial variation was best captured by CHELSA 2.1, which has finer spatial resolution. Our ability to quantify performance was constrained by limited data availability, even in this region with relatively many high-quality long-term in situ datasets, highlighting the need for more investment in ground-based data collection.[@Hemingway1952]
